version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-local
    restart: always
    environment:
      MONGO_INITDB_DATABASE: retailStoreDB
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["mongod"]

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
volumes:
  mongo-data:
